version: 2

updates:
    - package-ecosystem: gomod
      directory: /
      schedule:
          interval: weekly
      groups:
          go-dependencies:
              patterns: ["*"]
      ignore:
          -   dependency-name: google.golang.org/grpc
              versions: [ "1.84.0" ]
      commit-message:
          prefix: build
          include: scope