service_name: svc-user
shutdown_timeout: 10s

grpc:
    addr: ${GRPC_ADDR}
    reflection: ${GRPC_REFLECTION:-false}

postgres:
    dsn: "${POSTGRES_DSN}"
    max_conns: 10
    min_conns: 2
    max_conn_lifetime: 1h
    max_conn_idle_time: 30m
    health_check_period: 1m
    connect_timeout: 5s
    ping_timeout: 2s

log:
    level: info
    format: text